### ISSUE TITLE
Allow to pass more than one CSV input as parameter (IDFGH-13936)

### ISSUE THREAD

**Issue by stkw0** [espressif/esp-idf-nvs-partition-gen#8]
### Checklist

- [X] Checked the issue tracker for similar issues to ensure this is not a duplicate.
- [X] Described the feature in detail and justified the reason for the request.
- [X] Provided specific use cases and examples.

### Feature description

Currently, esp-idf-nvs-partition-gen only allows a single CSV as a parameter. I would like to allow to pass two CSV. Each CSV would have a different namespace and by passing two different CSV I could get a NVS binary partition that contains a set of two different namespace with his values. 

### Use cases

In our system we calibrate the different boards. Each board has their own calibration values. There are calibrations for a temperature sensor and for another sensor. Each sensor has his own CSV with his own namespace.

When we tried to generate a NVS partition containing both namespaces, we found it was not possible.

### Alternatives

Alternatively, it could be a single namespace and have each key reflect to which sensor they refer to. We would like to avoid that as they are two unrelated sensors and a board can have calibrations for one of the two but not the other. We also store each set of CSV in different places.

**Comment by pacucha42** [comment]
Hi @stkw0, thank you very much for the quick fix.
We shall check and merge your PR asap, just one question: did you consider/try generating the same namespace from multiple CVS? No problem if not, we can add it in some follow-up update, together with a fix for the failure of genrating multiple namespaces in the same CVS

**Comment by stkw0** [comment]
Yes. If there are two files and the two CSV use the same namespace but have different values it will generate a partition with all values in the correct namespace. The two namespace with the same name will get a different ID. I don't know if it would be preferred to merge different namespace that share the same name under the same namespace or it should print an error. I am not that familiar with the internals, so I didn't touched anything from the internal logic.

**Comment by pacucha42** [comment]
Thanks for the check!
The namespace is defined by its name, so I would expect merging all the corresponding records from any number of sources. My colleague already started working on your PR, so I'll ask for taking care of the namespace merging too.

Thank you for you contribution.

**Comment by adokitkat** [comment]
Hello. Thank you for your contribution. I just wanted to tell you I am using your MR as a base of the improvement and adding other commits like merging (practically omitting) duplicate namespaces in CSV files and just changing current namespace index for next written entries. However this doesn't fix the issue of having duplicate keys under the same namespace. This is how it will work:

| file1.csv | file2.csv | |
| - | - | - |
| **namespace: storage, idx: 1** | **~~namespace: storage, idx: 1~~** | this is OK, namespaces will "merge" now, so it won't be written again to the NVS and won't create a duplicate namespace name with different index number |
| key: val0, value: 123, namespace: 1 | key: val1, value: 123, namespace: 1 | this is also OK, same namespace but different keys |
| key: abc, value: 0, namespace: 1 | key: abc, value: 42, namespace: 1 | this is WRONG, 2 same keys in the same namespace, don't do this |
| **namespace: wifi, idx: 2** |  | |
| key: ssid, value: -1, idx: 2 |  | |
| | **namespace: test, idx: 3** | since you use 2 files and the generator reads them continuously, this namespace will get index number 3 (namespace indexes 1 and 2 are in the other file, the first namespace in this file is ignored because it is a duplicate) |
| | key: val0, value: 0, idx: 3 | OK, val0 was used before but in different namespace |

The generator will allow you to make this mistake because of the current implementation, that's why I am explaining it.
